import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import { useStateContext } from "@/context/state-context";
import { motion as m } from "framer-motion";

import speakingBubble from "../assets/speaking-bubble.png";
import talkingRobot from "../assets/talking-robot.png";

export default function Home() {
  const { setActiveSection } = useStateContext();
  const delay = 0.5;

  useEffect(() => {
    setActiveSection("index");
  }, []);
  return (
    <>
      <Head>
        <title>Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <m.div
        initial={{ y: "100%" }}
        animate={{ y: "0%" }}
        transition={{ duration: 0.75, ease: "easeOut" }}
        exit={{ x: "-100%" }}
        className="h-screen absolute top-0 left-0 w-full flex items-end"
      >
        <div className="py-20 flex flex-col items-center mx-auto">
          <div className="flex items-center flex-col mb-4 px-4 rounded-2xl overflow-hidden">
            <m.h3
              initial={{ opacity: 0 }}
              animate={{ opacity: 100 }}
              transition={{ delay: 0.5, duration: 0.75 }}
              className="backdrop-contrast-100 backdrop-blur-sm text-xl text-gray-800 py-1"
            >
              THE ARTIFICIAL INTELLIGENCE
            </m.h3>
            <m.h1
              initial={{ y: 100 }}
              animate={{ y: 0 }}
              transition={{ delay: 0.25, duration: 0.75 }}
              className="backdrop-contrast-100 font-extrabold text-transparent text-7xl bg-clip-text 
                          bg-gradient-to-r from-sky-400 via-sky-500 to-cyan-400"
            >
              EXPLORER
            </m.h1>
          </div>
          <div className="backdrop-contrast-100 pb-8 text-center">
            <p className="px-4 py-1 text-white">
              Explore the amazing powers of artificial intelligence
            </p>
            <p className="px-4 py-1 text-white">
              through image and text generation
            </p>
          </div>
          <div className="flex flex-col text-center gap-4">
            <Link
              className="bg-rose-500 font-bold border-2 border-black px-12 py-2 rounded-full
                          transition-all duration-200 hover:bg-rose-400"
              href={"/image-generation"}
            >
              TRY IMAGES
            </Link>
            <Link
              className="bg-rose-500 font-bold border-2 border-black px-12 py-2 rounded-full
                          transition-all duration-200 hover:bg-rose-400"
              href={"/text-generation"}
            >
              TRY TEXT
            </Link>
          </div>
        </div>
        <>
          <m.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 100 }}
            transition={{ delay: delay + 0.25, duration: 0.5 }}
            className="absolute top-36 left-20 w-40"
          >
            <Image
              className="w-full h-full object-cover"
              alt="text"
              src={speakingBubble}
              height={200}
              width={200}
            />
            <div className="rounded-lg max-h-[10rem] overflow-scroll text-ellipsis absolute top-0 max-w-[80%] ml-5 mt-3">
              <Link className="underline" href={"/feed"}>
                Click here to see what the community has created!
              </Link>
            </div>
          </m.div>

          <m.div
            initial={{ opacity: 0, x: -100 }}
            animate={{ opacity: 100, x: 0 }}
            transition={{ delay, duration: 0.5 }}
            className="absolute top-52 -left-10 w-40"
          >
            <Image
              className="w-full h-full object-cover"
              alt="robot"
              src={talkingRobot}
              height={200}
              width={200}
            />
          </m.div>
        </>
      </m.div>
    </>
  );
}
