import Navbar from "@/components/navbar";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState, useRef } from "react";

import TextGeneration from "./text-generation";
import ImageGeneration from "./image-generation";

export default function Home() {
  return (
    <>
      <Head>
        <title>GPTorger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-br from-gray-900 to-slate-700 min-h-screen h-fit">
        Welcome
      </main>
    </>
  );
}
