import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { FaAngleDown, FaAngleUp } from "react-icons/fa";

export default function Home() {
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [question, setQuestion] = useState("");
  const [showMenu, setShowMenu] = useState(false);

  const getData = async (e: any) => {
    e.preventDefault();
    setLoading(true);
    const prompt = question;

    const response = await fetch("/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt,
      }),
    });
    const data = response.body;
    if (!data) return;

    const reader = data.getReader();
    const decoder = new TextDecoder();
    let done = false;

    while (!done) {
      const { value, done: doneReading } = await reader.read();
      done = doneReading;
      const chunk = decoder.decode(value);
      setText((prev) => (prev += chunk));
    }

    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-br from-gray-900 to-slate-700 min-h-screen h-fit">
        <nav className=" bg-gradient-to-b from-gray-100 to-slate-300 relative shadow-lg">
          <h1
            className="font-extrabold text-transparent text-7xl bg-clip-text 
                      bg-gradient-to-br from-purple-500 to-sky-400 text-center
                      flex justify-center py-6"
          >
            GPTorger
            {/* <p className=" animate-spin">🤣</p> */}
          </h1>
          <div
            onClick={() => setShowMenu(!showMenu)}
            className="text-4xl flex justify-center items-center 
                          absolute top-0 right-0 mr-8 mt-12 hover:cursor-pointer"
          >
            {showMenu ? (
              <i>
                <FaAngleUp />
              </i>
            ) : (
              <i>
                <FaAngleDown />
              </i>
            )}
          </div>
        </nav>
        {showMenu && (
          <div className="relative w-screen">
            <div className="bg-slate-300 absolute right-0 w-1/5 flex justify-center py-2">
              <h3>Menu</h3>
            </div>
          </div>
        )}

        <form className="flex flex-col items-center mt-24">
          <textarea
            id="textfield"
            className="bg-gradient-to-br from-gray-100 to-slate-300 
                      rounded-2xl px-4 py-2 w-3/4 min-h-[6rem] max-h-[12rem] overflow-x-scroll"
            value={question}
            onChange={(e) => {
              setQuestion(e.currentTarget.value);
            }}
            onKeyDown={(e) => {
              if (e.keyCode === 13) getData(e);
            }}
            onClick={() => {
              setText("");
              setQuestion("");
            }}
            placeholder="Ask me something . . ."
          />
          <div className="flex">
            {loading ? (
              <button
                disabled
                type="button"
                className="bg-sky-600 
                      text-gray-200 font-bold 
                      rounded-2xl w-20 px-4 py-2 mt-8 h-10 mx-2
                      flex justify-center items-center
                      hover:cursor-not-allowed"
              >
                <svg
                  aria-hidden="true"
                  role="status"
                  className="inline w-4 h-4 text-gray-200 animate-spin"
                  viewBox="0 0 100 101"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                    fill="currentColor"
                  />
                  <path
                    d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                    fill="#FFF"
                  />
                </svg>
              </button>
            ) : (
              <button
                className="bg-sky-500 
                      text-gray-100 font-bold 
                      rounded-2xl w-20 px-4 py-2 mt-8 h-10 mx-2
                      transition-all ease-in-out duration-300
                      hover:bg-sky-600 hover:text-gray-200"
                type="button"
                onClick={(e) => {
                  setText("");
                  getData(e);
                }}
              >
                Go!
              </button>
            )}
            {
              <button
                className={`bg-gray-100 text-sky-500 font-bold border-2 border-sky-500 
                      flex justify-center items-center
                      rounded-2xl w-20 px-4 py-2 mt-8 h-10 mx-2
                      transition-all ease-in-out duration-300
                      hover:bg-sky-500 hover:text-gray-100`}
                onClick={(e) => {
                  e.preventDefault();
                  document.getElementById("textfield")?.focus();
                  setText("");
                  setQuestion("");
                }}
              >
                New
              </button>
            }
          </div>
        </form>

        {text.length > 0 && (
          <div
            className=" bg-gradient-to-b from-gray-100 to-slate-300 
                          min-h-[12rem] max-h-64 overflow-x-scroll 
                          w-3/4 rounded-xl mx-auto px-4 pt-4 pb-6 mt-12
                          text-xl"
          >
            <h3></h3>
            {text}
          </div>
        )}
      </main>
    </>
  );
}
